version: '3'
services:
  imm_netapp:
    image: imm_netapp_img
    container_name: imm_netapp_container
    environment:
      NETAPP_ID: "${netapp_id}"
      NETAPP_NAME: "${netapp_name}"
      NETAPP_IP: "${netapp_ip}"
      NETAPP_SERVER_VAPP: "${netapp_server_vapp}"
      NETAPP_PORT_5G: "${netapp_port_5g}"
      NETAPP_PORT_WEB: "${netapp_port_web}"
      NETAPP_PORT_VAPP: "${netapp_port_vapp}"
      NEF_EMULATOR_LOCALHOST: "${nef_emulator_localhost}"
      NEF_HOST: "${nef_host}"

    build:
      context: ./ 
    ports:
      # If port mapping is needed, left is host side and right is container side according to https://docs.docker.com/compose/compose-file/#ports
      - "9876:9876"
      - "9877:9877"
      - "9998:9998"
      - "9999:9999"
      
networks:
  default:
    name: nef_emulator_default
    external: true
      